sudo: false
language: sourcepawn

addons:
  apt_packages:
    - lib32stdc++6

matrix:
  fast_finish: true
  allow_failures:
    - env: SOURCEMOD=1.10

env:
  - SOURCEMOD=1.8
  - SOURCEMOD=1.9
  - SOURCEMOD=1.10

before_script:
  - wget "https://www.sourcemod.net/latest.php?version=$SOURCEMOD&os=linux" -O sourcemod-$SOURCEMOD-linux.tar.gz
  - tar -xzf sourcemod-$SOURCEMOD-linux.tar.gz
  - mv sbpp_discord.sp addons/sourcemod/scripting/
  - cd addons/sourcemod/scripting/
  - wget https://raw.githubusercontent.com/sbpp/sourcebans-pp/v1.x/game/addons/sourcemod/scripting/include/sourcebanspp.inc -O include/sourcebanspp.inc
  - wget https://raw.githubusercontent.com/sbpp/sourcebans-pp/v1.x/game/addons/sourcemod/scripting/include/sourcecomms.inc -O include/sourcecomms.inc
  - wget https://raw.githubusercontent.com/KyleSanderson/SteamWorks/master/Pawn/includes/SteamWorks.inc -O include/SteamWorks.inc
  - wget https://raw.githubusercontent.com/thraaawn/SMJansson/master/pawn/scripting/include/smjansson.inc -O include/smjansson.inc
  - chmod +x spcomp

script:
  - ./compile.sh sbpp_discord.sp

deploy:
  provider: releases
  api_key: "$githubkey"
  file: "$TRAVIS_BUILD_DIR/addons/sourcemod/scripting/compiled/sbpp_discord.smx"
  skip_cleanup: true
  on:
    tags: true
    condition: $SOURCEMOD = 1.9

notifications:
  email: false
